import type { Metadata } from "next";
import { Roboto } from "next/font/google"
import "../styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
//import { useState} from 'react'

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [menu, toggleMenu] = useState();
  return (
    <html lang="en" className={roboto.className}>
      <body>
       <Header/>
        <main>
        {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
